### ISSUE TITLE
Doesnt have prod-vaulues-yaml 

### ISSUE THREAD

**Issue by anillingutla** [ReadyTalk/vault-helm-chart#31] opened 2018-03-29 18:45 UTC
Issue 1 - 
helm install --values helm_charts/vault/values-prod.yaml --name vault-prod --namespace vault helm_charts/vault
Doesnt have the values-prod.yaml

Issue 2 - 
Error: failed to download "helm_charts/vault"
Where is the correct path.. first command itself is failing...

**Comment by bartlettc22** [comment] 2018-04-03 21:38
Dupe of #32

**Closed by bartlettc22** 2018-04-03 21:38 UTC
